### ISSUE TITLE
USBKVM only seems to work one way

### ISSUE THREAD

**Issue by AshleyHow** [NedWilbur/USBKVM#1]
Thanks for the neet application.

I have 2 x Dell U2414H monitors. MON1 (DisplayPort) -> MON2 (MiniDisplayPort that is daisy-chained from MON1) this works effectively as a single monitor.

When switching monitor from PC1 (personal PC) to PC2 (work PC) it works fine but fails to switch back. Almost as if the command has not been sent or sent too early? The settings are as the below. I have removed the hostnames.

`<Settings>
  <PC1 Name="REMOVED"></PC1>
  <PC2 Name="REMOVED"></PC2>
  <Monitor Name="292K475E0LDL" PC1_Input="15" PC2_Input="16"></Monitor>
</Settings>
`

I getting the following output in the app:

USBHub Disconnected
        Switching '292K475E0LDL' to '15'... Done!
USBHub Connected
        Switching '292K475E0LDL' to '16'... Done!

The values of 60 (Input Select) are correct as when running ControlMyControl on each PC and setting the value for the opposite input it works as expected. I do not have the software running on the work PC as don't really want it running there all the time and brings further complications.

Can you help please?

**Comment by NedWilbur** [comment]
Hi ah-uk. I should have some time to look at it tonight (EST, in 7 or so hours)

**Comment by AshleyHow** [comment]
Thanks, let me know if you need anything further.

**Comment by NedWilbur** [comment]
Based on the logs, the logic is working properly and the USBHub switch is being properly detected. I would say a daisy-chained setup like this may not be supported, but since it works one way, there is no reason it should not work the other way. My first guess is that the input number is not correct. Check it and try again.

If this does not work, try running ControlMyMonitor.exe and manually setting the input number within ControlMyMonitor to ensure it is working properly. If ControlMyMonitor is not working properly, unfortunately, USBKVM will not either.
![image](https://user-images.githubusercontent.com/19377058/108013478-c3e3ba80-6fd9-11eb-8088-52fa3b3527f5.png)

Hope this helps!

**Comment by AshleyHow** [comment]
Thanks for looking into this further. Unfortunately as said I have already tied it manually with ControlMyMonitor.exe and it works fine.

After some more thought as to what the difference may be I think I might know what is going on here. I think that DDC/CI commands will only be sent if a device is currently connected and is able to retrieve them. This explains why it only works one way.

Initially on my personal PC I have an active connection to my monitor via DP to send the DDC/CI command to switch from Input Select 16 -> 15. This works fine with the USBKVM application running on my personal PC. When on the work PC and switch via the switch button on my USB hub this this does not work. It finally dawned upon me that at this point my personal PC does not have any possible way to send a DDC/CI command back to switch Input Select from 15 -> 16 as as far as the PC is concerned there is no currently monitor connected.

I suspect that this will work fine if you have the application running on both PCs as that way a monitor is always available to retrieve a DDC/CI command. I presume you have it on both and that's how you have been testing it?

I'm going to confirm this later by running on both and will post an update.

**Comment by NedWilbur** [comment]
I have tested it with it running on only one machine and it works for me. I am using a command provided by ControlMyMonitor that only switches it if it detects it is not already on it (`/SetValueIfNeeded`). There is another command we can try that forces the monitor to change regardless (`/SetValue`). Try using the below commands in a batch file from your one machine. The first is similar to how USBKVM does it. The second is a more "forced" method that I could easily add to USBKVM if this resolves the issue for you. When run, it should switch to input `15`, wait for 5 seconds, then switch back to input `16`.

Current method:
``` bat
ControlMyMonitor.exe /SetValueIfNeeded "292K475E0LDL" 60 15
Sleep 5
ControlMyMonitor.exe /SetValueIfNeeded "292K475E0LDL" 60 16
```
"Forced" method:
``` bat
ControlMyMonitor.exe /SetValue "292K475E0LDL" 60 15
Sleep 5
ControlMyMonitor.exe /SetValue "292K475E0LDL" 60 16
```

**Comment by AshleyHow** [comment]
Thanks again, are you using display port out of interest?

Neither of those methods worked, I'm afraid. It was a good suggestion for sure.

I think that my monitor refuses to accept DDC/CI commands unless it is the current active monitor on the PC you are running the command from. Which would kind of make sense really. I have had a look to see if there was an option to turn this off (like an energy saving setting) but there doesn't seem to be. Guess I'll be sticking to manually switching the input via the monitor for the time being.

**Comment by NedWilbur** [comment]
Sorry for the delayed reply, just had a new baby :). Sorry to hear it is not working. Found out this exists too (after I made this), maybe it will work better for you: https://github.com/haimgel/display-switch
